### ISSUE TITLE
Add whitelisting for wp_safe_remote_get()

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Footer-Plugin#2]
Whitelisting for domains to allow the social menu and main footer menu feed urls to be fetched should be added for compatibility with wp_safe_remote_get().

Similar issue noted here:
https://github.com/UCF/UCF-Events-Plugin/pull/6

https://github.com/UCF/UCF-Footer-Plugin/blob/83df1e5f955eb02f80d81fa7c6be5acb209f4df2/includes/ucf-footer-feed.php#L17

**Comment by jmbarne3** [comment]
I think we could potentially go the same route with this as we did with the UCF-News-Plugin: https://github.com/UCF/UCF-News-Plugin/pull/8. Since the url is set by an administrator, it's not necessarily "arbitrary" and might make more sense to use the `wp_remote_get`function.

**Comment by jmbarne3** [comment]
Solved #3
